### PR TITLE
Fixed import for py3

### PR DESCRIPTION
**Pull request by skrzypek**

### CODE REVIEW

**Comment by Mirio** [comment]
Hi,
This change work only if the file is loaded by current directory (without install via pip or somethings).

**Comment by skrzypek** [comment]
Well, I have `venv` with pip install.

**Comment by skrzypek** [comment]
```
Traceback (most recent call last):
  File "dispatcher.py", line 459, in <module>
    process_batch(take_screenshots=False)
  File "dispatcher.py", line 327, in process_batch
    from scrape_worker import ScrapeWorker, file_folder_setup
  File "C:\scrapy_api_test\scrape_worker.py", line 21, in <module>
    from captcha2upload import CaptchaUpload
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\captcha2upload\__init__.py", line 1, in <module>
    from captcha2upload import CaptchaUpload
ImportError: cannot import name 'CaptchaUpload'

C:\scrapy_api_test>pwd
/c/scrapy_api_test
```

**Comment by Mirio** [comment]
Captcha2upload atm is not compatible with py3.
The issue on py3 is only import ?

**Comment by Mirio** [comment]
I test it locally and commit the changes.
Thanks

**Pull request closed without merging**
